Repository Happi-Cat-Tiger/Happi-Day-Front, pull requests merged in 2023-12, with the labels that each got.

#6 [Feature] 버튼 컴포넌트 UI 제작
  pnpm-lock.yaml
  src/components/Button/LoginButton.tsx
  src/components/Button/PrimaryButton.tsx
  src/components/Button/SubmitButton.tsx
Labels: enhancement, good first issue

#16 [WIP] Modal 컴포넌트 구현 (버튼 제외)
  package-lock.json
  package.json
  src/app/auth/signUp/layout.tsx
  src/app/layout.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/components/Modal/Modal.tsx
  src/styles/global.css
  tailwind.config.ts
  with-tailwindcss-app/.gitignore
  with-tailwindcss-app/README.md
Labels: work in progress

#10 [Feature] 게시판 레이아웃 작업
  pnpm-lock.yaml
  src/app/board/all/layout.tsx
  src/app/board/all/page.tsx
  src/app/board/events/layout.tsx
  src/app/board/events/page.tsx
  src/app/board/free/layout.tsx
  src/app/board/free/page.tsx
  src/app/board/friendship/layout.tsx
  src/app/board/friendship/page.tsx
  src/app/board/layout.tsx
  src/app/board/organizing/layout.tsx
  src/app/board/organizing/page.tsx
  src/app/board/page.tsx
  src/app/board/trade/layout.tsx
  src/app/board/trade/page.tsx
  src/app/board/write/layout.tsx
  src/app/board/write/page.tsx
Labels: enhancement
